{% set name = "spyder-line-profiler" %}
{% set version = "0.3.1" %}
{% set hash = "12df55049fe24ca524f1169e0f37ea8dfa61a9f4f217ac38fab321523f37b538" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - setuptools
  host:
    - pip
    - python >=3.7
  run:
    - line_profiler
    - python >=3.7
    - qtawesome
    - spyder >=5.2,<6

test:
  # On Linux, importing requires an X server
  imports:
    - spyder_line_profiler  # [not linux]

about:
  home: https://github.com/spyder-ide/spyder-line-profiler
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin that integrates the Python line profiler.
  description: |
    This is a plugin for the Spyder IDE that integrates the Python line profiler.
    It allows you to see the time spent in every line.
  dev_url: https://github.com/spyder-ide/spyder-line-profiler

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
    - jitseniesen
