travis:
  secure:
    BINSTAR_TOKEN: IoAaJk/Pm4dxKVpGtI89Nu0bvRsdd8BMB6osxbWRMzr/1xaNHazQl376RLz4qpVEkOfIHdMfWoDh/v4pr2wejOgKoyscndXjMvaxVNKo+ldAOBTKKzy37XAfJV7WP6xp2JO54VgiTQayUm5ZcsAw1J5oD1EOvXqDm71dny95W7q/ors9sAE6v1YMQhcXhrqVi1XjIfnyCDEXlwrYt+mPwLfnD54zf18TlQyaKPF56TpG1vHYyFhC0/HkR4t6BqHbVYiVt/+2NNw9YvxYtpHoJdG4Z871EwBJPvfBgwd110mPQuO1P/KVYS5yV0V1Un0KuN8qOJ4DYdX77pdn7LORvO8Ej2zgdskg2A+hdwp2tNdiml6847Ql6cx7fkCmqqNZH7r1bugY+8QGWgiC6fJn9DDrSipMzSgerVz/+Xii3aL3zJwh0/yJx7ZUZHzRFUTHqAXrb7qioks95WsrPDupRvJKvduly75GC8ARVnxGjyH27kTmw18tYxoiM4H97kL/zLIgVaLIbS6fvkiVImovlOZ1RsD6IKEIhNixCYUH57y0lV9Zve/Ml81tCpsra8Vg32ALAkFLJ5NECVxhnI+RGwmRBmpiQE/gyYT1okbiYu8gDprA5ORsgyV1ZMYCr3ROd6LKqPSJSToRsiQXgPq8lwiRLLI3wStgjNOkLIlcP40=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
